server:
  port: 8416
  servlet:
    context-path: /sso

spring:
  application:
    name: guns-sso-server
  profiles:
    active: loal
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /pages
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aioc?allowPublicKeyRetrieval=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: li206842
    db-name: tainjin_aioc_new #用来搜集数据库的所有表
    filters: wall,mergeStat
  aop:
    auto: true
    proxy-target-class: true
  redis:
    database: 0
    host: 116.196.88.6
    port: 6379
#    pool:
#      max-active: 10
#      max-wait: -1
#      max-idle: 2
    timeout: 5000
    password: ABCdef123
  jta:
    log-dir: ./ssoserver-log
mybatis-plus:
  typeAliasesPackage: com.stylefeng.sso.server.modular.entity

cors:
  origins: http://localhost:8083

log:
  path: sso-server
