server:
  port: 8516
  servlet:
    context-path: /sso

spring:
  application:
    name: guns-sso-server
  profiles:
    active: test
  mvc:
#    static-path-pattern: /static/**
    view:
      prefix:  /pages
  datasource:
    url: jdbc:mysql://mysql-cn-north-1-4fda8775bfcc4f32.public.jcloud.com:3306/tianjin_aioc_new?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: aioc
    password: i8NnFvh6t
    db-name: tainjin_aioc_new #用来搜集数据库的所有表
    filters: wall,mergeStat
  aop:
    auto: true
    proxy-target-class: true
  redis:
    database: 0
    host: 116.196.88.6
    port: 6379
    pool:
      max-active: 10
      max-wait: -1
      max-idle: 2
    timeout: 5000
    password: ABCdef123
mybatis-plus:
  typeAliasesPackage: com.stylefeng.sso.server.modular.entity

log:
  path: sso-server
