server:
  port: 8116
  servlet:
    context-path: /sso

spring:
  application:
    name: guns-sso-server
  profiles:
    active: skw
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  datasource:
    url: jdbc:mysql://mysql-cn-north-1-d785b9ea5251484a.public.jcloud.com:3306/aioc?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: cluster_mysql
    password: Centos73
  aop:
    auto: true
    proxy-target-class: true

mybatis-plus:
  typeAliasesPackage: com.stylefeng.sso.server.modular.entity

log:
  path: sso-server