server:
  port: 8146
  servlet:
    context-path: /sso

spring:
  application:
    name: guns-sso-server
  profiles:
    active: dev
  mvc:
#    static-path-pattern: /static/**
    view:
      prefix: /pages
  datasource:
    url: jdbc:mysql://mysql-cn-north-1-4fda8775bfcc4f32.public.jcloud.com:3306/tianjin_aioc_new?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: aioc
    password: i8NnFvh6t
#    db-name: tainjin_aioc_new #用来搜集数据库的所有表
    filters: wall,mergeStat
  aop:
    auto: true
    proxy-target-class: true
  redis:
    database: 0
    host: 116.196.88.6
    port: 6379
    pool:
      max-active: 10
      max-wait: -1
      max-idle: 2
    timeout: 5000
    password: ABCdef123
  jta:
      log-dir: ./ssoserver-log
mybatis-plus:
  typeAliasesPackage: com.stylefeng.sso.server.modular.entity

# 跨域配置
cors:
  origins: http://116.196.123.140,http://116.196.123.140:8085,http://116.196.123.140:8083,http://116.196.123.140:8082,http://116.196.123.140:8081,http://116.196.123.140:8080,http://localhost,http://localhost:8085,http://localhost:8083,http://localhost:8082,http://localhost:8081,http://localhost:8080,http://116.196.89.151,http://116.196.89.151:8085,http://116.196.89.151:8083,http://116.196.89.151:8082,http://116.196.89.151:8081,http://116.196.89.151:8080,http://192.168.0.159,http://192.168.0.159:8085,http://192.168.0.159:8083,http://192.168.0.159:8082,http://192.168.0.159:8081,http://192.168.0.159:8080

log:
  path: sso-server