server:
  port: 8516
  servlet:
    context-path: /sso

spring:
  application:
    name: guns-sso-server
  profiles:
    active: pri
  mvc:
#    static-path-pattern: /static/**
    view:
      prefix:  /pages
  datasource:
    url: jdbc:mysql://192.168.0.129:3306/aioc?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1990@Mysql
  aop:
    auto: true
    proxy-target-class: true
  redis:
    database: 0
    host: 192.168.0.158
    port: 6379
    pool:
      max-active: 10
      max-wait: -1
      max-idle: 2
    timeout: 5000
    password: GPQJG2rHjo2ifNqj
  jta:
    log-dir: ./ssoserver-log
mybatis-plus:
  typeAliasesPackage: com.stylefeng.sso.server.modular.entity

cors:
  origins: http://192.168.0.159,http://192.168.0.159:8085,http://192.168.0.159:8083,http://192.168.0.159:8082,http://192.168.0.159:8081,http://192.168.0.159:8080

log:
  path: sso-server